# Generated by Django 5.1.2 on 2024-12-23 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_address_address_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(error_messages={'unique': 'A user with that phone number already exists.'}, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid phone number', message='Enter a valid phone number.', regex='^989[0-39]\\d{8}$')], verbose_name='phone number'),
        ),
    ]
